apiVersion: v1
kind: Service
metadata:
  name: hotel-app
  namespace: hotel-reservation
spec:
  type: NodePort
  selector:
    app: hotel-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
